const fs = require('fs');
const path = require('path');

const localesPath = path.join(__dirname, 'src/locales');

const newKeys = {
    vi: {
        "services_list": "Danh sách Dịch vụ",
        "add_service": "Thêm dịch vụ",
        "table_image": "Hình ảnh",
        "table_service_name": "Tên dịch vụ",
        "table_short_desc": "Mô tả ngắn",
        "import_failed": "Nhập thất bại",
        "import_completed": "Hoàn tất nhập",
        "import_success_count": "thành công",
        "import_failed_count": "thất bại",
        "download_template": "Tải file mẫu",
        "import_excel": "Nhập Excel",
        "export_excel": "Xuất Excel",
        "add_post": "Thêm bài viết",
        "table_title": "Tiêu đề",
        "table_author": "Tác giả",
        "table_category": "Chuyên mục",
        "table_date": "Ngày",
        "table_actions": "Hành động",
        "unknown": "Không rõ",
        "add_new_category": "Thêm chuyên mục mới",
        "category_name": "Tên chuyên mục",
        "add_new": "Thêm mới",
        "blog_management_page_desc": "Tạo, sửa, xóa các bài viết và chuyên mục blog.",
        "order_status_pending": "Chờ xác nhận",
        "order_status_processing": "Đang xử lý",
        "order_status_shipped": "Đang giao",
        "order_status_completed": "Hoàn thành",
        "order_status_cancelled": "Đã hủy",
        "order_status_refunded": "Hoàn tiền",
        "expired_status": "Hết hạn",
        "out_of_stock_status": "Hết hàng",
        "low_stock_status": "Sắp hết hàng",
        "near_expiry_status": "Cận date",
        "in_stock_status": "Còn hàng",
        "filter_all": "Tất cả",
        "filter_in_stock": "Còn hàng",
        "filter_low_stock": "Sắp hết/Cận date",
        "filter_out_of_stock": "Hết hàng/Hết hạn",
        "manage_products": "Quản lý Sản phẩm",
        "manage_orders": "Quản lý Đơn hàng",
        "ghtk_settings": "Cài đặt GHTK",
        "products_list": "Danh sách Sản phẩm",
        "add_product": "Thêm Sản phẩm",
        "table_product": "Sản phẩm",
        "table_sku": "Mã SKU",
        "table_price": "Giá bán",
        "table_stock": "Tồn kho",
        "table_status": "Trạng thái",
        "table_expiry": "HSD",
        "table_order_code": "Mã đơn hàng",
        "table_customer": "Khách hàng",
        "table_order_date": "Ngày đặt",
        "table_total_price": "Tổng tiền",
        "table_shipping": "Vận chuyển",
        "tab_general": "Cài đặt chung",
        "tab_homepage": "Trang chủ",
        "tab_about": "Trang Giới thiệu",
        "tab_faq": "Câu hỏi thường gặp (FAQ)"
    },
    en: {
        "services_list": "Services List",
        "add_service": "Add Service",
        "table_image": "Image",
        "table_service_name": "Service Name",
        "table_short_desc": "Short Description",
        "import_failed": "Import failed",
        "import_completed": "Import completed",
        "import_success_count": "successful",
        "import_failed_count": "failed",
        "download_template": "Download Template",
        "import_excel": "Import Excel",
        "export_excel": "Export Excel",
        "add_post": "Add Post",
        "table_title": "Title",
        "table_author": "Author",
        "table_category": "Category",
        "table_date": "Date",
        "table_actions": "Actions",
        "unknown": "Unknown",
        "add_new_category": "Add New Category",
        "category_name": "Category Name",
        "add_new": "Add New",
        "blog_management_page_desc": "Create, edit, and delete blog posts and categories.",
        "order_status_pending": "Pending",
        "order_status_processing": "Processing",
        "order_status_shipped": "Shipped",
        "order_status_completed": "Completed",
        "order_status_cancelled": "Cancelled",
        "order_status_refunded": "Refunded",
        "expired_status": "Expired",
        "out_of_stock_status": "Out of Stock",
        "low_stock_status": "Low Stock",
        "near_expiry_status": "Near Expiry",
        "in_stock_status": "In Stock",
        "filter_all": "All",
        "filter_in_stock": "In Stock",
        "filter_low_stock": "Low/Near Expiry",
        "filter_out_of_stock": "Out/Expired",
        "manage_products": "Manage Products",
        "manage_orders": "Manage Orders",
        "ghtk_settings": "GHTK Settings",
        "products_list": "Products List",
        "add_product": "Add Product",
        "table_product": "Product",
        "table_sku": "SKU",
        "table_price": "Price",
        "table_stock": "Stock",
        "table_status": "Status",
        "table_expiry": "Expiry Date",
        "table_order_code": "Order Code",
        "table_customer": "Customer",
        "table_order_date": "Order Date",
        "table_total_price": "Total Price",
        "table_shipping": "Shipping",
        "tab_general": "General Settings",
        "tab_homepage": "Homepage",
        "tab_about": "About Page",
        "tab_faq": "FAQ"
    },
    ru: {
        "services_list": "Список услуг",
        "add_service": "Добавить услугу",
        "table_image": "Изображение",
        "table_service_name": "Название услуги",
        "table_short_desc": "Краткое описание",
        "import_failed": "Ошибка импорта",
        "import_completed": "Импорт завершен",
        "import_success_count": "успешно",
        "import_failed_count": "ошибка(ок)",
        "download_template": "Скачать шаблон",
        "import_excel": "Импорт Excel",
        "export_excel": "Экспорт Excel",
        "add_post": "Добавить статью",
        "table_title": "Заголовок",
        "table_author": "Автор",
        "table_category": "Категория",
        "table_date": "Дата",
        "table_actions": "Действия",
        "unknown": "Неизвестно",
        "add_new_category": "Новая категория",
        "category_name": "Название категории",
        "add_new": "Добавить",
        "blog_management_page_desc": "Управление статьями и категориями блога.",
        "order_status_pending": "Ожидается",
        "order_status_processing": "В обработке",
        "order_status_shipped": "Отправлено",
        "order_status_completed": "Завершено",
        "order_status_cancelled": "Отменено",
        "order_status_refunded": "Возврат",
        "expired_status": "Срок годности истек",
        "out_of_stock_status": "Нет в наличии",
        "low_stock_status": "Мало на складе",
        "near_expiry_status": "Истекает срок",
        "in_stock_status": "В наличии",
        "filter_all": "Все",
        "filter_in_stock": "В наличии",
        "filter_low_stock": "Мало/Истекает",
        "filter_out_of_stock": "Нет/Истек",
        "manage_products": "Управление товарами",
        "manage_orders": "Управление заказами",
        "ghtk_settings": "Настройки GHTK",
        "products_list": "Список товаров",
        "add_product": "Добавить товар",
        "table_product": "Товар",
        "table_sku": "SKU",
        "table_price": "Цена",
        "table_stock": "Количество",
        "table_status": "Статус",
        "table_expiry": "Срок годности",
        "table_order_code": "Код заказа",
        "table_customer": "Клиент",
        "table_order_date": "Дата заказа",
        "table_total_price": "Общая сумма",
        "table_shipping": "Доставка",
        "tab_general": "Общие настройки",
        "tab_homepage": "Главная",
        "tab_about": "О нас",
        "tab_faq": "FAQ"
    },
    cn: {
        "services_list": "服务列表",
        "add_service": "添加服务",
        "table_image": "图片",
        "table_service_name": "服务名称",
        "table_short_desc": "简短描述",
        "import_failed": "导入失败",
        "import_completed": "导入完成",
        "import_success_count": "成功",
        "import_failed_count": "失败",
        "download_template": "下载模板",
        "import_excel": "导入Excel",
        "export_excel": "导出Excel",
        "add_post": "添加文章",
        "table_title": "标题",
        "table_author": "作者",
        "table_category": "类别",
        "table_date": "日期",
        "table_actions": "操作",
        "unknown": "未知",
        "add_new_category": "添加新类别",
        "category_name": "类别名称",
        "add_new": "添加",
        "blog_management_page_desc": "创建，编辑和删除博客文章和类别。",
        "order_status_pending": "待处理",
        "order_status_processing": "处理中",
        "order_status_shipped": "已发货",
        "order_status_completed": "已完成",
        "order_status_cancelled": "已取消",
        "order_status_refunded": "已退款",
        "expired_status": "已过期",
        "out_of_stock_status": "缺货",
        "low_stock_status": "库存不足",
        "near_expiry_status": "临近过期",
        "in_stock_status": "有货",
        "filter_all": "全部",
        "filter_in_stock": "有货",
        "filter_low_stock": "库存不足/临期",
        "filter_out_of_stock": "缺货/过期",
        "manage_products": "管理产品",
        "manage_orders": "管理订单",
        "ghtk_settings": "GHTK 设置",
        "products_list": "产品列表",
        "add_product": "添加产品",
        "table_product": "产品",
        "table_sku": "SKU",
        "table_price": "价格",
        "table_stock": "库存",
        "table_status": "状态",
        "table_expiry": "有效期",
        "table_order_code": "订单代码",
        "table_customer": "顾客",
        "table_order_date": "订单日期",
        "table_total_price": "总价",
        "table_shipping": "配送",
        "tab_general": "常规设置",
        "tab_homepage": "主页",
        "tab_about": "关于页面",
        "tab_faq": "常见问题"
    }
};

const langs = ['vi', 'en', 'ru', 'cn'];

langs.forEach(lang => {
    const filePath = path.join(localesPath, lang, 'translation.json');
    if (fs.existsSync(filePath)) {
        const rawData = fs.readFileSync(filePath, 'utf-8');
        const jsonData = JSON.parse(rawData);

        if (!jsonData.admin) {
            jsonData.admin = {};
        }

        Object.assign(jsonData.admin, newKeys[lang]);

        fs.writeFileSync(filePath, JSON.stringify(jsonData, null, 4));
        console.log(`Updated ${lang}/translation.json`);
    } else {
        console.error(`File not found: ${filePath}`);
    }
});
