
export type AdminUserSection = 'doctors' | 'roles';
export type AdminBlogSection = 'posts' | 'seo_queue' | 'image_queue' | 'categories';
export type AdminDashboardSection = 'overview' | 'customers' | 'appointments' | 'reports';
export type AdminPharmacySection = 'products' | 'categories' | 'brands' | 'discounts' | 'taxes' | 'orders' | 'ghtk_settings';
export type AdminSiteSection = 'branding' | 'footer' | 'auth' | 'payment' | 'homepage' | 'about' | 'faq' | 'observability';
export type AdminPharmacyOrderPreset = 'all' | 'priority_queue' | 'shipping_handover' | 'bank_transfer_followup' | 'refund_attention' | 'today_watch';
export type AdminPharmacyProductFilter = 'all' | 'in_stock' | 'low_stock' | 'out_of_stock' | 'hidden' | 'featured' | 'near_expiry' | 'no_sku';

export type AdminNavigationView =
  | { page: 'adminDashboard', section?: AdminDashboardSection }
  | { page: 'adminUserManagement', section?: AdminUserSection }
  | { page: 'adminBlogManagement', section?: AdminBlogSection }
  | { page: 'adminServiceManagement' }
  | { page: 'adminImageLibrary' }
  | { page: 'adminProductImageImporter' }
  | { page: 'adminPancakeManagement' }
  | {
      page: 'adminPharmacyManagement',
      section?: AdminPharmacySection,
      action?: 'new-product' | 'order-detail',
      orderId?: string,
      orderPreset?: AdminPharmacyOrderPreset,
      productFilter?: AdminPharmacyProductFilter,
    }
  | { page: 'adminSiteManagement', section?: AdminSiteSection, action?: 'observability' };

export type View =
  | { page: 'main' }
  | { page: 'services' }
  | { page: 'serviceDetail', id: number | string }
  | { page: 'about' }
  | { page: 'blog' }
  | { page: 'blogCategory', categorySlug: string }
  | { page: 'blogDetail', slug: string, categorySlug?: string }
  | { page: 'ingredientAnalyzer' }
  | { page: 'brands' }
  | { page: 'brandLanding', brandSlug: string }
  | { page: 'products', brandSlug?: string, searchQuery?: string }
  | { page: 'productsCategory', categorySlug: string, brandSlug?: string, searchQuery?: string }
  | { page: 'productDetail', id: number | string, categorySlug?: string, focusReview?: boolean }
  | { page: 'cart' }
  | { page: 'checkout' }
  | { page: 'checkoutSuccess' }
  | { page: 'orderLookup' }
  | { page: 'wishlist' }
  | { page: 'account' }
  | { page: 'administrativeProfile' }
  | { page: 'medicalRecords' }
  | { page: 'myMedicalRecords' }
  | { page: 'appointments' }
  | { page: 'booking', serviceId?: number }
  | { page: 'auth' }
  | { page: 'orderHistory' }
  | AdminNavigationView;


export interface ProcedureStep {
  id: number;
  step_number: number;
  title: string;
  description: string;
  title_en?: string;
  title_ru?: string;
  title_cn?: string;
  description_en?: string;
  description_ru?: string;
  description_cn?: string;
  image_path?: string;
  image_url?: string; // Generated by API
}

export interface DetailFaqEntry {
  question: string;
  answer: string;
}

export interface Service {
  id: number;
  slug?: string;
  name: string;
  description: string;
  long_description: string;
  benefits: string[];
  name_en?: string;
  name_ru?: string;
  name_cn?: string;
  description_en?: string;
  description_ru?: string;
  description_cn?: string;
  long_description_en?: string;
  long_description_ru?: string;
  long_description_cn?: string;
  benefits_en?: string[];
  benefits_ru?: string[];
  benefits_cn?: string[];
  icon: string; // Keep as string, will be mapped to component
  price: number;
  image_path?: string;
  image_url?: string; // Generated by API
  procedure_steps: ProcedureStep[];
  faq_items?: DetailFaqEntry[];
  local_seo_tags?: string[];
}

export interface Doctor {
  id: string; // This is the user UUID from patients table
  name: string;
  avatar_path?: string;
  avatar_url?: string; // Generated by API
  job_title?: string;
  specialization?: string;
  description?: string; // from doctors.homepage_description
  job_title_en?: string;
  job_title_ru?: string;
  job_title_cn?: string;
  specialization_en?: string;
  specialization_ru?: string;
  specialization_cn?: string;
  description_en?: string; // homepage_description_en
  description_ru?: string; // homepage_description_ru
  description_cn?: string; // homepage_description_cn
}

export interface BlogCategory {
  slug: string;
  name: string;
  name_en?: string;
  name_ru?: string;
  name_cn?: string;
}

export interface BlogPost {
  slug: string;
  title: string;
  summary: string;
  content: string;
  detail_loaded?: boolean;
  title_en?: string;
  title_ru?: string;
  title_cn?: string;
  summary_en?: string;
  summary_ru?: string;
  summary_cn?: string;
  content_en?: string;
  content_ru?: string;
  content_cn?: string;
  author_id: string; // UUID of the author from 'patients' table
  date: string;
  category_slug: string;
  image_path: string;
  image_url?: string; // Generated by API
  author?: Pick<PatientProfile, 'id' | 'name' | 'avatar_path' | 'avatar_url'>; // Embedded author info
  // SEO Fields
  meta_description?: string;
  meta_keywords?: string; // comma-separated
  canonical_url?: string;
  local_seo_tags?: string[];
}

export interface PatientProfile {
  id: string;
  name: string;
  dob: string;
  phone: string;
  email: string;
  address_street?: string;
  address_ward?: string;
  address_district?: string;
  address_province?: string;
  gender: 'male' | 'female' | 'other';
  citizen_id_number: string;
  nationality: string;
  medical_history?: string;
  skin_type?: string;
  allergies?: string;
  avatar_path?: string;
  avatar_url?: string; // Generated by API
  role: 'customer' | 'doctor' | 'admin' | 'master_admin';
}

export interface Appointment {
  id: string;
  service_id: number;
  doctor_id: string; // Changed to string (uuid)
  date: string;
  time: string;
  notes?: string;
  status: 'pending' | 'confirmed' | 'completed' | 'cancelled';
}

export interface PerformedService {
  id: string;
  name: string;
  price: number;
  notes?: string;
}

export interface PrescribedMedication {
  id: string;
  name: string;
  dosage: string;
  quantity: number;
  unit: string;
  price: number;
  notes?: string;
}

export interface Invoice {
  id: string;
  total_amount: number;
  payment_status: 'paid' | 'unpaid' | 'partial';
  payment_method: string;
  payment_date?: string;
}

export interface MedicalRecord {
  id: string;
  appointment_id: string;
  encounter_date: string;
  examining_doctor_id: string; // Changed to string (uuid)
  preliminary_diagnoses_icd_codes: string[];
  definitive_diagnoses_icd_codes: string[];
  clinical_notes: string;
  services: PerformedService[];
  prescriptions: PrescribedMedication[];
  invoice: Invoice;
}

export interface PatientDocument {
  id: string;
  patient_id: string;
  file_path: string;
  file_name: string;
  mime_type: string;
  ai_summary: string | null;
  created_at: string;
  public_url?: string;
}

export interface UserData {
  profile: PatientProfile;
  appointments: Appointment[];
  medical_records: MedicalRecord[];
  documents: PatientDocument[];
  wishlist: number[]; // Array of product IDs
  product_orders: ProductOrder[];
  detail_loaded?: boolean;
}

export interface FAQItem {
  id: number;
  question: string;
  answer: string;
  question_en?: string;
  question_ru?: string;
  question_cn?: string;
  answer_en?: string;
  answer_ru?: string;
  answer_cn?: string;
}

export interface AboutFeature {
  id: string;
  icon: string;
  title: string;
  description: string;
  title_en?: string;
  description_en?: string;
  title_ru?: string;
  description_ru?: string;
  title_cn?: string;
  description_cn?: string;
  display_order?: number;
}

export interface AboutValue {
  id: string;
  title: string;
  description: string;
  title_en?: string;
  description_en?: string;
  title_ru?: string;
  description_ru?: string;
  title_cn?: string;
  description_cn?: string;
  icon: string;
  display_order?: number;
}

// This matches the 'about_page_content' table in Supabase
export interface AboutContent {
  id?: 1;
  header_title: string;
  header_subtitle: string;
  header_title_en?: string;
  header_subtitle_en?: string;
  header_title_ru?: string;
  header_subtitle_ru?: string;
  header_title_cn?: string;
  header_subtitle_cn?: string;
  image_path: string;
  image_url?: string;
  mission_title: string;
  mission_text: string;
  vision_text: string;
  values_title: string;
  values_subtitle: string;
  mission_title_en?: string;
  mission_text_en?: string;
  vision_text_en?: string;
  values_title_en?: string;
  values_subtitle_en?: string;
  mission_title_ru?: string;
  mission_text_ru?: string;
  vision_text_ru?: string;
  values_title_ru?: string;
  values_subtitle_ru?: string;
  mission_title_cn?: string;
  mission_text_cn?: string;
  vision_text_cn?: string;
  values_title_cn?: string;
  values_subtitle_cn?: string;
}

export interface AboutPageData {
  content: AboutContent;
  reasonsToChoose: AboutFeature[];
  coreValues: AboutValue[];
}

export interface Source {
  uri: string;
  title: string;
}

export interface GeminiResponse {
  text: string;
  sources: Source[];
}

export interface DoctorProfile {
  id: string; // patient id
  username: string;
  job_title?: string;
  specialization?: string;
  qualification?: string;
  homepage_description?: string;
  practice_license_code?: string;
  job_title_en?: string;
  job_title_ru?: string;
  job_title_cn?: string;
  specialization_en?: string;
  specialization_ru?: string;
  specialization_cn?: string;
  homepage_description_en?: string;
  homepage_description_ru?: string;
  homepage_description_cn?: string;
}

export interface DoctorDetail extends PatientProfile {
  doctor_profile: DoctorProfile | null;
}

export interface HomepageHero {
  id?: number;
  title: string;
  subtitle: string;
  title_en?: string;
  title_ru?: string;
  title_cn?: string;
  subtitle_en?: string;
  subtitle_ru?: string;
  subtitle_cn?: string;
  image_desktop_path: string;
  image_desktop_url?: string;
  image_desktop_avif_url?: string;
  image_tablet_path?: string;
  image_tablet_url?: string;
  image_tablet_avif_url?: string;
  image_mobile_path?: string;
  image_mobile_url?: string;
  image_mobile_avif_url?: string;
  cta_text?: string;
}

export interface AuthPageImages {
  id?: number;
  login_image_path: string;
  login_image_url?: string;
}

export interface SiteInfo {
  id?: number;
  clinic_name: string;
  logo_light_path: string;
  logo_dark_path: string;
  favicon_path: string;
  logo_light_url?: string; // Generated by API
  logo_dark_url?: string; // Generated by API
  favicon_url?: string; // Generated by API
}

export interface FooterContent {
  id?: number;
  about_text: string;
  address: string;
  phone: string;
  email: string;
  working_hours_weekday: string;
  working_hours_weekend: string;
  copyright_text: string;
  about_text_en?: string;
  about_text_ru?: string;
  about_text_cn?: string;
  copyright_text_en?: string;
  copyright_text_ru?: string;
  copyright_text_cn?: string;
  facebook_url?: string;
  instagram_url?: string;
  youtube_url?: string;
  tiktok_url?: string;
  zalo_url?: string;
  messenger_url?: string;
  floating_contact_enabled?: boolean;
}

export interface PaymentSettings {
  id?: number;
  bank_bin: string;
  account_number: string;
  account_holder_name: string;
}

export interface ProductCategory {
  id: number;
  name: string;
  slug: string;
  description?: string;
  name_en?: string;
  name_ru?: string;
  name_cn?: string;
  description_en?: string;
  description_ru?: string;
  description_cn?: string;
  is_featured?: boolean;
}

export interface ProductImage {
  id: number;
  product_id: number;
  image_url: string;
  image_path: string;
  display_order: number;
  is_primary: boolean;
}

export interface ProductBrand {
  id: number;
  name: string;
  slug: string;
  description?: string;
  logo_path?: string;
  logo_url?: string;
}

export type ProductContentBlock =
  | { type: 'text'; content: string }
  | { type: 'image'; image_path: string; image_url?: string; caption?: string };


export interface Product {
  id: number;
  name: string;
  slug: string;
  category_slug?: string;
  description: string;
  detail_loaded?: boolean;
  long_description?: ProductContentBlock[];
  price: number;
  vat_rate?: number;
  stock_quantity: number;
  sku?: string;
  expiry_date?: string; // Stored as 'YYYY-MM-DD'
  low_stock_threshold?: number;
  category_id?: number;
  usage_instructions?: string;
  ingredients?: string;
  is_published: boolean;
  is_featured?: boolean;
  archived_at?: string | null;
  source_updated_at?: string;
  updated_at?: string;
  sold_count?: number;
  key_benefits?: string[];
  skin_types?: string[];
  volume?: string;
  texture?: string;
  origin?: string;
  precautions?: string;
  brand?: string;
  // Translation fields
  name_en?: string;
  name_ru?: string;
  name_cn?: string;
  description_en?: string;
  description_ru?: string;
  description_cn?: string;
  usage_instructions_en?: string;
  usage_instructions_ru?: string;
  usage_instructions_cn?: string;
  ingredients_en?: string;
  ingredients_ru?: string;
  ingredients_cn?: string;
  key_benefits_en?: string[];
  key_benefits_ru?: string[];
  key_benefits_cn?: string[];
  precautions_en?: string;
  precautions_ru?: string;
  precautions_cn?: string;
  texture_en?: string;
  texture_ru?: string;
  texture_cn?: string;
  origin_en?: string;
  origin_ru?: string;
  origin_cn?: string;
  category?: ProductCategory; // for joining
  images?: ProductImage[];
  faq_items?: DetailFaqEntry[];
}

export type ProductContentReviewStatus = 'needs_review' | 'in_review' | 'rewrite_requested' | 'approved';
export type ProductContentIssueSeverity = 'blocker' | 'warning';

export interface ProductContentIssue {
  code: string;
  field: string;
  severity: ProductContentIssueSeverity;
  message: string;
}

export interface ProductContentAudit {
  score: number;
  blocker_count: number;
  warning_count: number;
  issues: ProductContentIssue[];
  summary: string;
  content_signature: string;
}

export interface ProductContentReviewRecord {
  product_id: number;
  review_status: ProductContentReviewStatus;
  review_notes: string;
  rewrite_brief: string;
  audit_score: number;
  blocker_count: number;
  warning_count: number;
  issues: ProductContentIssue[];
  content_signature: string;
  reviewed_at: string;
  reviewed_by: string;
  reviewed_by_label?: string;
  updated_at: string;
}

export interface ProductReview {
  id: string;
  product_id: number;
  user_id: string;
  rating: number;
  title: string;
  comment: string;
  created_at: string;
  verified_purchase?: boolean;
  author: Pick<PatientProfile, 'name' | 'avatar_url' | 'avatar_path'>;
}

// E-commerce & Cart Types
export interface CartItem extends Product {
  quantity: number;
}

export interface ShippingAddress {
  fullName: string;
  phone: string;
  email: string;
  street: string;
  ward: string;
  district: string;
  province: string;
  notes?: string;
}

export type OrderPaymentMethod = 'cod' | 'bank_transfer';
export type OrderPaymentStatus = 'unpaid' | 'paid' | 'failed' | 'refunded';
export type OrderFulfillmentStatus = 'pending' | 'processing' | 'shipped' | 'completed' | 'cancelled';

export interface OrderStatusHistory {
  id: string;
  order_id: string;
  from_status?: OrderFulfillmentStatus | null;
  to_status: OrderFulfillmentStatus;
  actor_id?: string | null;
  actor_role?: string | null;
  note?: string | null;
  created_at: string;
}

export interface OrderPaymentLog {
  id: string;
  order_id: string;
  method: OrderPaymentMethod;
  amount: number;
  status: OrderPaymentStatus;
  transaction_ref?: string | null;
  paid_at?: string | null;
  metadata?: Record<string, any>;
  created_at: string;
}

export interface OrderRefundLog {
  id: string;
  order_id: string;
  amount: number;
  reason?: string | null;
  status: 'pending' | 'completed' | 'failed';
  restocked: boolean;
  refunded_at?: string | null;
  created_by?: string | null;
  created_at: string;
}

export interface AdminDashboardKpiSnapshot {
  total_orders: number;
  paid_orders: number;
  pending_orders: number;
  completed_orders: number;
  cancelled_orders: number;
  refunded_orders: number;
  guest_orders: number;
  gross_revenue: number;
  net_revenue: number;
  discount_total: number;
  tax_total: number;
  shipping_total: number;
  refund_total: number;
  average_order_value: number;
  total_customers: number;
  new_customers: number;
  returning_customers: number;
  appointments_total: number;
  appointments_pending: number;
  appointments_completed: number;
  appointments_cancelled: number;
  service_revenue: number;
}

export interface AdminDashboardTimeseriesPoint {
  bucket_start: string;
  total_orders: number;
  paid_orders: number;
  gross_revenue: number;
  net_revenue: number;
  refund_total: number;
  appointments_total: number;
}

export interface AdminInventoryMetrics {
  total_products: number;
  published_products: number;
  featured_products: number;
  hidden_products: number;
  in_stock_products: number;
  low_stock_products: number;
  out_of_stock_products: number;
  near_expiry_products: number;
  no_sku_products: number;
  inventory_estimated_value: number;
}

export interface AdminCustomerMetric {
  patient_id: string;
  name: string;
  email: string;
  phone: string;
  created_at: string;
  total_orders: number;
  total_spent: number;
  average_order_value: number;
  first_order_at?: string | null;
  last_order_at?: string | null;
  total_appointments: number;
  last_appointment_at?: string | null;
  orders_in_period: number;
  spent_in_period: number;
  segment: 'hybrid_customer' | 'product_only_customer' | 'service_only_customer' | 'lead_only_customer';
  is_at_risk: boolean;
  is_returning: boolean;
}

export interface AdminDashboardAlert {
  alert_key: string;
  alert_type: string;
  severity: 'critical' | 'high' | 'medium' | 'low';
  title: string;
  description: string;
  ref_type: string;
  ref_id: string;
  created_at: string;
}

export interface AdminBulkOrderTransitionResult {
  order_id: string;
  ok: boolean;
  error_message: string | null;
  order_data?: ProductOrder | null;
}

export type AdminReportPreset = '7d' | '30d' | '90d';
export type AdminReportFrequency = 'daily' | 'weekly';

export interface AdminReportSchedule {
  id: string;
  name: string;
  preset: AdminReportPreset;
  frequency: AdminReportFrequency;
  day_of_week: number | null;
  hour_local: number;
  minute_local: number;
  timezone: string;
  recipients: string[];
  enabled: boolean;
  next_run_at: string | null;
  last_sent_at: string | null;
  last_error_at: string | null;
  last_error_message: string | null;
  created_at: string;
  updated_at: string;
}

export interface ObservabilityRetentionState {
  last_run_at: string | null;
  last_reason: string | null;
  last_status: 'idle' | 'running' | 'completed' | 'failed';
  days_to_keep: number;
  matched_count: number;
  deleted_count: number;
  deleted_keys_sample: string[];
  error_message: string | null;
}

export interface ObservabilityLogEntry {
  key: string;
  recorded_at: string;
  channel: string;
  type?: string;
  message?: string;
  context?: string;
  path?: string;
  href?: string;
  resource?: string;
  source?: string;
  status?: number;
  cf_ray?: string;
  user_agent?: string;
  body_preview?: string;
  details?: string;
  stack?: string;
}

export interface ObservabilityLogsResponse {
  logs: ObservabilityLogEntry[];
  limit: number;
  days: number;
  scanned_prefixes: number;
  scanned_objects: number;
  has_more: boolean;
  retention: ObservabilityRetentionState | null;
}

export interface ObservabilityMetricRollup {
  request_count: number;
  cache_hits: number;
  cache_misses: number;
  cache_hit_rate: number;
  upstream_timeouts: number;
  upstream_timeout_rate: number;
  error_count: number;
  error_rate: number;
  partial_count: number;
  partial_rate: number;
  p50_ms: number | null;
  p95_ms: number | null;
  max_ms: number | null;
  last_seen_at: string | null;
}

export interface ObservabilityMetricEndpointSummary extends ObservabilityMetricRollup {
  endpoint: string;
  resource?: string;
}

export interface ObservabilityMetricsSummaryResponse {
  generated_at: string;
  days: number;
  scanned_prefixes: number;
  scanned_objects: number;
  has_more: boolean;
  totals: ObservabilityMetricRollup;
  endpoints: ObservabilityMetricEndpointSummary[];
}

export interface ObservabilityCleanupResult {
  dry_run: boolean;
  days_to_keep: number;
  cutoff_iso: string;
  scanned_prefixes: number;
  scanned_objects: number;
  matched_count: number;
  deleted_count: number;
  deleted_keys_sample: string[];
  retention: ObservabilityRetentionState;
}

export interface AdminEditorDraftRecord<T = unknown> {
  draft_key: string;
  saved_at: string;
  data: T;
  updated_by: string;
  source: 'server';
}

export interface AdminEditorDraftResponse<T = unknown> {
  draft: AdminEditorDraftRecord<T> | null;
}

export interface AdminEditorDraftDeleteResult {
  deleted: boolean;
  draft_key: string;
}

export interface ProductContentReviewListResponse {
  reviews: ProductContentReviewRecord[];
}

export interface ProductContentReviewUpsertResponse {
  review: ProductContentReviewRecord | null;
}

export interface AdminTopProductMetric {
  product_id: number;
  product_name: string;
  brand: string;
  units_sold: number;
  order_count: number;
  gross_revenue: number;
}

export interface AdminServicePerformanceMetric {
  service_id: number;
  service_name: string;
  appointment_count: number;
  completed_count: number;
  cancelled_count: number;
  pending_count: number;
  realized_revenue: number;
}

export interface AdminAppointmentDrilldown {
  id: string;
  patient_id: string;
  patient_name: string;
  patient_email: string;
  patient_phone: string;
  doctor_id: string;
  doctor_name: string;
  service_id: number;
  service_name: string;
  date: string;
  time: string;
  notes: string;
  status: Appointment['status'];
  created_at: string;
  updated_at: string;
  invoice_total_amount: number;
  invoice_payment_status: '' | Invoice['payment_status'];
  invoice_payment_method: string;
  invoice_payment_date: string | null;
}

export interface ProductOrder {
  id: string; // uuid
  user_id?: string; // uuid, nullable for guest checkout
  order_code?: string;
  checkout_idempotency_key?: string | null;
  subtotal_price?: number;
  discount_code?: string | null;
  discount_amount?: number;
  total_price: number;
  status: 'pending' | 'processing' | 'shipped' | 'completed' | 'cancelled' | 'refunded';
  payment_method?: OrderPaymentMethod;
  payment_status?: OrderPaymentStatus;
  fulfillment_status?: OrderFulfillmentStatus;
  customer_name: string;
  customer_phone: string;
  customer_email?: string | null;
  locale?: 'vi' | 'en' | 'ru' | 'cn';
  shipping_street: string;
  shipping_ward: string;
  shipping_district: string;
  shipping_province: string;
  notes?: string;
  created_at: string;
  shipping_provider?: string;
  shipping_fee?: number;
  shipping_net_amount?: number;
  shipping_tax_rate?: number;
  shipping_tax_amount?: number;
  shipping_code?: string;
  ghtk_label?: string; // GHTK shipment ID
  ghtk_status_text?: string; // GHTK status text
  tax_profile_id?: string | null;
  tax_mode?: 'exclusive' | 'inclusive' | null;
  tax_rate?: number;
  taxable_amount?: number;
  tax_amount?: number;
  currency?: string;
  grand_total?: number;
  estimated_delivery_time?: string;
  order_items?: ProductOrderItem[];
  status_history?: OrderStatusHistory[];
  payment_logs?: OrderPaymentLog[];
  refund_logs?: OrderRefundLog[];
}

export interface ProductOrderItem {
  id: string; // uuid
  order_id: string; // uuid
  product_id: number;
  product_name?: string | null;
  product_sku?: string | null;
  product_image_path?: string | null;
  resolved_product_image_path?: string | null;
  quantity: number;
  price_at_purchase: number;
  product?: Partial<Product & { main_image_url?: string }>;
}

export interface DiscountCode {
  id?: string;
  code: string;
  type: 'percentage' | 'fixed_amount';
  value: number;
  min_purchase_amount?: number;
  max_discount_amount?: number;
  preview_discount_amount?: number;
  starts_at?: string | null;
  ends_at?: string | null;
  usage_limit?: number | null;
  usage_limit_per_user?: number | null;
  usage_count?: number;
  is_active?: boolean;
  description?: string | null;
  created_at?: string;
  updated_at?: string;
}

export interface CheckoutPricingQuote {
  tax_profile_id?: string | null;
  tax_mode: 'exclusive' | 'inclusive';
  tax_rate: number;
  currency: string;
  subtotal: number;
  discount_amount: number;
  taxable_amount: number;
  tax_amount: number;
  shipping_net_amount: number;
  shipping_tax_rate?: number;
  shipping_tax_amount: number;
  shipping_fee: number;
  grand_total: number;
}

export interface TaxProfile {
  id?: string;
  code: string;
  name: string;
  tax_mode: 'exclusive' | 'inclusive';
  default_rate: number;
  applies_to_shipping: boolean;
  currency: string;
  is_active: boolean;
  is_default: boolean;
  starts_at?: string | null;
  ends_at?: string | null;
  created_at?: string;
  updated_at?: string;
  rates?: TaxRate[];
}

export interface TaxRate {
  id?: string;
  tax_profile_id: string;
  province?: string | null;
  district?: string | null;
  rate: number;
  applies_to_shipping?: boolean | null;
  currency?: string | null;
  priority: number;
  is_active: boolean;
  starts_at?: string | null;
  ends_at?: string | null;
  created_at?: string;
  updated_at?: string;
}

export interface GhtkTrackingEvent {
  status: string;
  timestamp: string;
  location: string;
}

export interface GhtkPickAddress {
  pick_address_id: string;
  pick_name: string;
  pick_address: string;
  pick_province: string;
  pick_district: string;
  pick_ward: string;
  pick_street: string;
  pick_tel: string;
  pick_email: string;
  is_default: 0 | 1;
}

export interface GhtkPickAddressDetail extends GhtkPickAddress {
  // As per documentation, get specific address has the same fields
  // as the list, so this can be empty for now but provides
  // semantic distinction.
}

/**
 * Returns a deterministic fallback image URL for a blog post based on its slug.
 * Picks one of the 18 predefined images from public/images/blog images/.
 */
export function getFallbackBlogImage(slug: string): string {
  let hash = 0;
  for (let i = 0; i < slug.length; i++) {
    hash = slug.charCodeAt(i) + ((hash << 5) - hash);
  }
  const index = (Math.abs(hash) % 18) + 1;
  return `/images/blog%20images/Blog%20Image%20${index}.webp`;
}
