CREATE TABLE IF NOT EXISTS public.product_brands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    description TEXT,
    logo_path TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- RLS policies
ALTER TABLE public.product_brands ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" ON public.product_brands
    FOR SELECT USING (true);

CREATE POLICY "Enable insert for authenticated users only" ON public.product_brands
    FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Enable update for authenticated users only" ON public.product_brands
    FOR UPDATE USING (auth.role() = 'authenticated');

CREATE POLICY "Enable delete for authenticated users only" ON public.product_brands
    FOR DELETE USING (auth.role() = 'authenticated');
